#ifndef DISPLAY_BACKEND_CONFIG_HPP
#define DISPLAY_BACKEND_CONFIG_HPP

#include "../platform/BoardConfig.hpp"

#define ROASTER_DISPLAY_BACKEND_LVGL 1

#ifndef ROASTER_DISPLAY_BACKEND
#define ROASTER_DISPLAY_BACKEND ROASTER_DISPLAY_BACKEND_LVGL
#endif

#endif