#ifndef DISPLAY_BACKEND_CONFIG_HPP
#define DISPLAY_BACKEND_CONFIG_HPP

#include "BoardConfig.hpp"

#define ROASTER_DISPLAY_BACKEND_NEXTION 0
#define ROASTER_DISPLAY_BACKEND_LVGL 1

#ifndef ROASTER_DISPLAY_BACKEND
#if ROASTER_TARGET_BOARD == ROASTER_BOARD_JC4827W543C
#define ROASTER_DISPLAY_BACKEND ROASTER_DISPLAY_BACKEND_LVGL
#else
#define ROASTER_DISPLAY_BACKEND ROASTER_DISPLAY_BACKEND_NEXTION
#endif
#endif

#endif